[flow.ash]
class = "ash"
prop_data = "ash"

[flow.ash.atoms]
C = {}
H = {}
O = {}
N = {}
S = {}
P = {}
K = {}
Cl = {}
Ca = {}
Al = {}
Fe = {}
Mg = {}
Mn = {}
Na = {}
Si = {}
Ti = {}
Zn = {}
Hg = {}
Pb = {}
Cd = {}
Cr = {}
Cu = {}
Ni = {}
As = {}

[flow.ash.molecules]
# n_data = 0 â†’ empty

[flow.ash.proximate]
DM = {}
H2O = {}
ash = {}
INORG = {}
ORG = {}
INORG-O = {}
ORG-O = {}
INORG-S = {}
ORG-S = {}
INORG-N = {}
ORG-N = {}

[flow.ash.properties]
rho_m = 400.0
cp_m = 1200.0
