[flow.SE_pellets_arbacore_spruce_stem]
class = "SE-pellets_hardwood"
prop_data = "solid_fuel"

[flow.SE_pellets_arbacore_spruce_stem.atoms]
C = {Y = 0.523}
H = {Y = 0.062}
O = {Y = 0.4139}
N = {Y = 0.001}
S = {Y = 0.0001}
Cl = {Y = 0.00002}

[flow.SE_pellets_arbacore_spruce_stem.proximate]
VOL = {Y = 0.802}
FC = {Y = 0.196}
ash = {Y = 0.0002}
H2O = {Y = 0.034}

[flow.SE_pellets_arbacore_spruce_stem.properties]
LHV = 20.9
rho_m = 400.0
cp_m = 1200.0

[flow.spruce_chips]
class = "hardwood"
prop_data = "solid_fuel"

[flow.spruce_chips.atoms]
C = {Y = 0.4878}
H = {Y = 0.0627}
O = {Y = 0.448}
N = {Y = 0.0013}
S = {Y = 0.0001}
Cl = {Y = 0.0}

[flow.spruce_chips.proximate]
VOL = {Y = 0.39985}
FC = {Y = 0.09825}
ash = {Y = 0.0019}
H2O = {Y = 0.05}

[flow.spruce_chips.properties]
HHV = 20.13
rho_m = 400.0
cp_m = 1200.0

[flow.spruce_stem]
class = "hardwood"
prop_data = "solid_fuel"

[flow.spruce_stem.atoms]
C = {Y = 0.4738}
H = {Y = 0.064}
O = {Y = 0.461}
N = {Y = 0.0009}
S = {Y = 0.0001}
Cl = {Y = 0.0}

[flow.spruce_stem.proximate]
VOL = {Y = 0.7243}
FC = {Y = 0.2727}
ash = {Y = 0.003}
H2O = {Y = 0.5}

[flow.spruce_stem.properties]
HHV = 19.9
rho_m = 400.0
cp_m = 1200.0

[flow.spruce_bark]
class = "hardwood"
prop_data = "solid_fuel"

[flow.spruce_bark.atoms]
C = {Y = 0.4909}
H = {Y = 0.0606}
O = {Y = 0.4438}
N = {Y = 0.0045}
S = {Y = 0.0002}
Cl = {Y = 0.0}

[flow.spruce_bark.proximate]
VOL = {Y = 0.7062}
FC = {Y = 0.2685}
ash = {Y = 0.0253}
H2O = {Y = 0.5}

[flow.spruce_bark.properties]
HHV = 20.25
rho_m = 400.0
cp_m = 1200.0

[flow.spruce_TandB]
class = "hardwood"
prop_data = "solid_fuel"

[flow.spruce_TandB.atoms]
C = {Y = 0.5153}
H = {Y = 0.0651}
O = {Y = 0.415}
N = {Y = 0.0044}
S = {Y = 0.0002}
Cl = {Y = 0.0}

[flow.spruce_TandB.proximate]
VOL = {Y = 0.6982}
FC = {Y = 0.2449}
ash = {Y = 0.0569}
H2O = {Y = 0.5}

[flow.spruce_TandB.properties]
HHV = 19.94
rho_m = 400.0
cp_m = 1200.0

[flow.birch_stem]
class = "woody_biomass"
prop_data = "solid_fuel"

[flow.birch_stem.atoms]
C = {Y = 0.4862}
H = {Y = 0.0634}
O = {Y = 0.449}
N = {Y = 0.0009}
S = {Y = 0.0005}
Cl = {Y = 0.0}

[flow.birch_stem.proximate]
VOL = {Y = 0.8943}
FC = {Y = 0.1035}
ash = {Y = 0.0022}
H2O = {Y = 0.5}

[flow.birch_stem.properties]
HHV = 18.42
rho_m = 400.0
cp_m = 1200.0
