[flow.water]
class = "water"
prop_data = "water_correlations"

[flow.water.molecules]
H2O = {Y = 1.0}

[flow.water.atoms]
H = {X = 2.0}
O = {X = 1.0}

[flow.water.properties]
HHV = -2.5
rho_m = 1000.0
cp_m = 1000.0


[flow.steam]
class = "water"
prop_data = "water_correlations"

[flow.steam.molecules]
H2O = {Y = 1.0}

[flow.steam.atoms]
H = {X = 2.0}
O = {X = 1.0}

[flow.steam.properties]
HHV = -2.5
rho_m = 1000.0
cp_m = 1000.0


[flow.H2O]
class = "water"
prop_data = "water_correlations"

[flow.H2O.molecules]
H2O = {Y = 1.0}

[flow.H2O.atoms]
H = {X = 2.0}
O = {X = 1.0}

[flow.H2O.properties]
HHV = -2.5
rho_m = 1000.0
cp_m = 1000.0

