[flow.H2O]
cls = "water"
flow_db = "Flows_database/Flows/Water_db.toml"

[flow.water]
cls = "water"
flow_db = "Flows_database/Flows/Water_db.toml"

[flow.steam]
cls = "water"
flow_db = "Flows_database/Flows/Water_db.toml"

[flow.air]
cls = "ideal_gas"
flow_db = "Flows_database/Flows/Gases_db.toml"

[flow.dry_air]
cls = "ideal_gas"
flow_db = "Flows_database/Flows/Gases_db.toml"

[flow.wet_air]
cls = "ideal_gas"
flow_db = "Flows_database/Flows/Gases_db.toml"

[flow.flue_gas]
cls = "ideal_gas"
flow_db = "Flows_database/Flows/Gases_db.toml"

[flow.ash]
cls = "ash"
flow_db = "Flows_database/Flows/Ash_db.toml"

[flow.spruce_chips]
cls = "hardwood"
flow_db = "Flows_database/Flows/Biomass_db.toml"

[flow.spruce_stem]
cls = "hardwood"
flow_db = "Flows_database/Flows/Biomass_db.toml"

[flow.spruce_TandB]
cls = "hardwood"
flow_db = "Flows_database/Flows/Biomass_db.toml"

[flow.spruce_bark]
cls = "hardwood"
flow_db = "Flows_database/Flows/Biomass_db.toml"

[flow.birch_stem]
cls = "hardwood"
flow_db = "Flows_database/Flows/Biomass_db.toml"

[flow.SE_pellets_arbacore_spruce_stem]
cls = "hardwood"
flow_db = "Flows_database/Flows/Biomass_db.toml"
