# -------- GASES --------------------------------------------------------------
[[flows]]
id = "flue_gas"
class = "ideal_gas"
prop_data = "NIST"
components = ["O2", "N2", "Ar", "H2O", "H2", "CO", "CO2", "SO2", "NO2"]

[[flows]]
id = "dry_air"
class = "ideal_gas"
prop_data = "NIST"
[flows.composition.mole]
N2 = 0.7812
Ar = 0.0092
O2 = 0.2096

[[flows]]
id = "wet_air"
class = "ideal_gas"
prop_data = "NIST"
[flows.composition.mole]
N2 = 0.7812
Ar = 0.0092
O2 = 0.2096
H2O = 0.0

# -------- WATER --------------------------------------------------------------
[[flows]]
id = "water"
class = "water"
prop_data = "water_correlations"
[flows.properties]
HHV_MJ_per_kg = -2.5
rho_m = 1000.0
cp_m = 1000.0

# -------- ASH (labels + properties only) ------------------------------------
[[flows]]
id = "ash"
class = "ash"
prop_data = "ash"
[flows.properties]
rho_m = 400.0
cp_m = 1200.0
[flows.proximate]
labels = ["DM", "H2O", "ash", "INORG", "ORG", "INORG-O", "ORG-O", "INORG-S", "ORG-S", "INORG-N", "ORG-N"]

# -------- BIOMASS ------------------------------------------------------------
[[flows]]
id = "SE-pellets_arbacore_spruce_stem"
class = "biomass"
prop_data = "solid_fuel"
[flows.ultimate.mass]
C = 0.523
H = 0.062
O = 0.4139
N = 0.001
S = 0.0001
Cl = 2e-05
[flows.proximate.mass]
VOL = 0.802
FC = 0.196
ASH = 0.0002
H2O = 0.034
[flows.properties]
LHV_MJ_per_kg = 20.9
rho_m = 400.0
cp_m = 1200.0

[[flows]]
id = "spruce_chips"
class = "biomass"
prop_data = "solid_fuel"
[flows.ultimate.mass]
C = 0.4878
H = 0.0627
O = 0.448
N = 0.0013
S = 0.0001
Cl = 0.0
[flows.proximate.mass]
VOL = 0.39985
FC = 0.09825
ASH = 0.0019
H2O = 0.05
[flows.properties]
HHV_MJ_per_kg = 20.13
rho_m = 400.0
cp_m = 1200.0

[[flows]]
id = "spruce_stem"
class = "biomass"
prop_data = "solid_fuel"
[flows.ultimate.mass]
C = 0.4738
H = 0.064
O = 0.461
N = 0.0009
S = 0.0001
Cl = 0.0
[flows.proximate.mass]
VOL = 0.7243
FC = 0.2727
ASH = 0.003
H2O = 0.5
[flows.properties]
HHV_MJ_per_kg = 19.9
rho_m = 400.0
cp_m = 1200.0

[[flows]]
id = "spruce_bark"
class = "biomass"
prop_data = "solid_fuel"
[flows.ultimate.mass]
C = 0.4909
H = 0.0606
O = 0.4438
N = 0.0045
S = 0.0002
Cl = 0.0
[flows.proximate.mass]
VOL = 0.7062
FC = 0.2685
ASH = 0.0253
H2O = 0.5
[flows.properties]
HHV_MJ_per_kg = 20.25
rho_m = 400.0
cp_m = 1200.0

[[flows]]
id = "spruce_T&B"
class = "biomass"
prop_data = "solid_fuel"
[flows.ultimate.mass]
C = 0.5153
H = 0.0651
O = 0.415
N = 0.0044
S = 0.0002
Cl = 0.0
[flows.proximate.mass]
VOL = 0.6982
FC = 0.2449
ASH = 0.0569
H2O = 0.5
[flows.properties]
HHV_MJ_per_kg = 19.94
rho_m = 400.0
cp_m = 1200.0

[[flows]]
id = "birch_stem"
class = "biomass"
prop_data = "solid_fuel"
[flows.ultimate.mass]
C = 0.4862
H = 0.0634
O = 0.449
N = 0.0009
S = 0.0005
Cl = 0.0
[flows.proximate.mass]
VOL = 0.8943
FC = 0.1035
ASH = 0.0022
H2O = 0.5
[flows.properties]
HHV_MJ_per_kg = 18.42
rho_m = 400.0
cp_m = 1200.0
